---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: false

platforms:
  - name: debian-7.7
    driver:
        box: opscode_debian-7.7_chef-11.16.4-1
        box_url: http://vagrant.pingworks.net/opscode_debian-7.7_chef-11.16.4-1.box
        network:
        - ["forwarded_port", { guest: 80, host: 8080 }]

#suites:
#  - name: dash-prod_and_repo
#    run_list:
#      - recipe[chef-dash::dash-prod]
#      - recipe[chef-dash::repo]
#    attributes: {}
suites:
  - name: dash-scripts
    run_list:
      - recipe[chef-dash::dash-scripts]
    attributes: {}
